SELECT AI.INVOICE_ID,
  NVL(PV.VENDOR_NAME, HP.PARTY_NAME) VENDOR_NAME,
  PV.SEGMENT1 VENDOR_NUMBER ,
  AI.INVOICE_NUM INVOICE_NUM,
  AI.INVOICE_CURRENCY_CODE,
  AI.INVOICE_AMOUNT INVOICE_AMOUNT,
  AI.INVOICE_DATE INVOICE_DATE ,
  AP_INVOICES_PKG.GET_PO_NUMBER( AI.INVOICE_ID) PO_NUMBER,
  -- AI.VOUCHER_NUM VOUCHER_NUM,AI.doc_sequence_id,
  AI.DOC_SEQUENCE_VALUE VOUCHER_NUM,
  AI.GL_DATE GL_DATE ,
  fuc.user_name CREATED_BY,
  AIAHA.approver_name LAST_UPDATED_BY,
  AI.exchange_rate ,
  HOU.name organization_name,
  Case When AP_INVOICES_PKG.GET_POSTING_STATUS( AI.INVOICE_ID)='Y' Then 'YES' Else 'NO' End Accounted_Status
FROM AP_INVOICES_ALL AI,
  (SELECT * FROM AP_INV_APRVL_HIST_ALL WHERE RESPONSE='APPROVED') AIAHA,
  PO_VENDORS PV,
  HZ_PARTIES HP,
  fnd_user fuc,
  hr_operating_UNITS HOU
WHERE AI.invoice_id=AIAHA.invoice_id(+)
AND PV.VENDOR_ID(+) = AI.VENDOR_ID
AND AI.PARTY_ID       = HP.PARTY_ID
AND AI.created_by     = fuc.user_id
AND AI.org_id         = HOU.organization_id
--AND AIAHA.RESPONSE='APPROVED'
AND AI.INVOICE_ID    = 23005
AND HOU.organization_id    = 82