
SELECT    &P_HINT_CLAUSE
    	LGR.NAME		LEDGER_NAME,
	LGR.CURRENCY_CODE	LEDGER_CURRENCY,
FU2.USER_NAME Generated_BY,
xxpj_get_cc_desc (GLL.code_combination_id) ACCT_DESC ,
                LGR.LEDGER_ID                       LEDGER_ID,
	GLB.JE_BATCH_ID		BATCH_ID,
    	GLB.NAME		BATCH_NAME,
	GLB.DESCRIPTION		BATCH_DESC,
	GLB.STATUS		BATCH_STATUS_CODE,
     	GLB.POSTED_DATE		BATCH_POSTED_DATE,
     	GLB.DEFAULT_PERIOD_NAME	BATCH_PERIOD_NAME,
     	GLB.DEFAULT_EFFECTIVE_DATE	BATCH_EFFECTIVE_DATE,
        	GLB.ACTUAL_FLAG			ACTUAL_FLAG, 
	GLB.AVERAGE_JOURNAL_FLAG	AVERAGE_JOURNAL_FLAG,
	GLB.APPROVAL_STATUS_CODE	APPROVAL_STATUS_CODE,
	GLB.BUDGETARY_CONTROL_STATUS	BUD_CONTROL_STATUS,
	GLB.RUNNING_TOTAL_DR	BATCH_TOT_DR,
	GLB.RUNNING_TOTAL_CR	BATCH_TOT_CR,
	GLB.RUNNING_TOTAL_ACCOUNTED_DR	BATCH_TOT_ACC_DR,
	GLB.RUNNING_TOTAL_ACCOUNTED_CR	BATCH_TOT_ACC_CR,
	GLB.DATE_CREATED	BATCH_DATE_CREATED,

	GLH.JE_HEADER_ID		HDR_ID,
	GLH.NAME		HDR_NAME,
	GLH.DESCRIPTION		HDR_DESC,
	GLH.TAX_STATUS_CODE	TAX_STATUS_CODE,
	GLH.RUNNING_TOTAL_DR	HDR_TOT_DR,
	GLH.RUNNING_TOTAL_CR	HDR_TOT_CR,
	GLH.RUNNING_TOTAL_ACCOUNTED_DR	HDR_TOT_ACC_DR,
	GLH.RUNNING_TOTAL_ACCOUNTED_CR	HDR_TOT_ACC_CR,
	GLH.CURRENCY_CODE	HDR_CURR_CODE,
	GLH.CURRENCY_CONVERSION_DATE	CONVERSION_DATE,
	GLH.CURRENCY_CONVERSION_RATE	CONVERSION_RATE,
	DCT.USER_CONVERSION_TYPE	CONVERSION_TYPE,
	GLH.BUDGET_VERSION_ID	BUDGET_VERSION_ID,
	GLH.ENCUMBRANCE_TYPE_ID	ENCUMBRANCE_TYPE_ID,
	GLH.EXTERNAL_REFERENCE	HDR_EXTREFERENCE,
	GLH.LAST_UPDATE_DATE	HDR_LAST_UPDATE_DATE,
	GLH.DEFAULT_EFFECTIVE_DATE	HDR_EFF_DATE,
                GLH.DOC_SEQUENCE_ID          DOC_SEQ_ID,
	DOCSEQ.NAME		DOC_SEQ_NAME,
	GLH.DOC_SEQUENCE_VALUE	DOC_SEQ_VALUE,
	FU.USER_NAME		HDR_LAST_UPDATED_BY,
	GJS.USER_JE_SOURCE_NAME	HDR_SOURCE,
	GJC.USER_JE_CATEGORY_NAME	HDR_CATEGORY,

	GLL.JE_LINE_NUM		JE_LINE_NUM,
	GLL.TAX_CODE_ID		TAX_CODE_ID,
	GLL.TAX_TYPE_CODE	TAX_TYPE_CODE,
	GLL.DESCRIPTION		LINE_DESC,
	GLL.ENTERED_DR		ENTERED_DR,
	GLL.ENTERED_CR		ENTERED_CR,
	GLL.ACCOUNTED_DR	ACCOUNTED_DR,
	GLL.ACCOUNTED_CR	ACCOUNTED_CR,
	GLL.STAT_AMOUNT		STAT_AMOUNT,
	GLL.EFFECTIVE_DATE	EFFECTIVE_DATE,
	GLL.REFERENCE_1		REFERENCE1,
	GLL.REFERENCE_2		REFERENCE2,
	GLL.REFERENCE_3		REFERENCE3,
	GLL.REFERENCE_4		REFERENCE4,
	GLL.REFERENCE_5		REFERENCE5,
	GLL.REFERENCE_6		REFERENCE6,
	GLL.REFERENCE_7		REFERENCE7,
	GLL.REFERENCE_8		REFERENCE8,
	GLL.REFERENCE_9		REFERENCE9,
	GLL.REFERENCE_10		REFERENCE10,
	SUBDOCSEQ.NAME		SUB_DOC_SEQ_NAME,
                GLL.SUBLEDGER_DOC_SEQUENCE_ID SUB_DOC_SEQ_ID,
	GLL.SUBLEDGER_DOC_SEQUENCE_VALUE	SUB_DOC_SEQ_VAL,
	 &SELECT_ACCOUNT		ACCOUNT,
	&SELECT_BAL_SEGMENT	BAL_SEG_VAL,
	&SELECT_ACCT_SEGMENT	ACCT_SEG_VAL,
	&SELECT_COST_CTR_SEGMENT	COST_CTR_SEG_VAL,
	&SELECT_SECONDARY_SEGMENT	ADDITIONAL_SEGMENT_VALUE

 FROM     &P_PERF_FROM
               &P_JOURNAL_FROM_CLAUSE 
               &P_LEDGER_FROM
WHERE GLH.LEDGER_ID = LGR.LEDGER_ID
 &P_LEDGER_WHERE
 AND  GLH.JE_SOURCE = GJS.JE_SOURCE_NAME
 AND  GLH.JE_CATEGORY  =  GJC.JE_CATEGORY_NAME
 AND  GLH.LAST_UPDATED_BY = FU.USER_ID
 AND  GLB.JE_BATCH_ID = GLH.JE_BATCH_ID
 AND  GLH.DOC_SEQUENCE_ID = DOCSEQ.DOC_SEQUENCE_ID(+)
 AND  GLL.SUBLEDGER_DOC_SEQUENCE_ID = SUBDOCSEQ.DOC_SEQUENCE_ID(+)
 AND DCT.CONVERSION_TYPE (+) = GLH.CURRENCY_CONVERSION_TYPE
&P_POSTING_STATUS
&P_HEADER_POSTING_STATUS
&P_DAS_WHERE
&P_CURRENCY_WHERE
&P_ACTUAL_TYPE_WHERE
&P_BATCH_WHERE
&P_SOURCE_WHERE
&P_CATEGORY_WHERE
&P_BAL_WHERE
&P_DOC_ID_WHERE
&P_DOC_VAL_WHERE
&P_SUB_DOC_ID_WHERE
&P_SUB_DOC_VAL_WHERE
&P_PERIOD_WHERE
&P_CONTRA_ACCOUNT_WHERE 
 &P_JOURNAL_DATE_WHERE
&P_JOURNAL_UPD_DATE_WHERE
&P_JOURNAL_LAST_UPD_WHERE
&P_AFF_WHERE
&P_AMOUNT_WHERE
&P_JOURNAL_WHERE_CLAUSE
 
******************************************************************************
SELECT   
    	LGR.NAME		LEDGER_NAME,
		LGR.CURRENCY_CODE	LEDGER_CURRENCY,
		LGR.LEDGER_ID                       LEDGER_ID,
		GLB.JE_BATCH_ID		BATCH_ID,
		GLB.NAME		BATCH_NAME,
		GLB.DESCRIPTION		BATCH_DESC,
		GLB.STATUS		BATCH_STATUS_CODE,
		GLB.POSTED_DATE		BATCH_POSTED_DATE,
		GLB.DEFAULT_PERIOD_NAME	BATCH_PERIOD_NAME,
		GLB.DEFAULT_EFFECTIVE_DATE	BATCH_EFFECTIVE_DATE,
		GLB.ACTUAL_FLAG			ACTUAL_FLAG, 
		GLB.AVERAGE_JOURNAL_FLAG	AVERAGE_JOURNAL_FLAG,
		GLB.APPROVAL_STATUS_CODE	APPROVAL_STATUS_CODE,
		GLB.BUDGETARY_CONTROL_STATUS	BUD_CONTROL_STATUS,
		GLB.RUNNING_TOTAL_DR	BATCH_TOT_DR,
		GLB.RUNNING_TOTAL_CR	BATCH_TOT_CR,
		GLB.RUNNING_TOTAL_ACCOUNTED_DR	BATCH_TOT_ACC_DR,
		GLB.RUNNING_TOTAL_ACCOUNTED_CR	BATCH_TOT_ACC_CR,
		GLB.DATE_CREATED	BATCH_DATE_CREATED,

	GLH.JE_HEADER_ID		HDR_ID,
	GLH.NAME		HDR_NAME,
	GLH.DESCRIPTION		HDR_DESC,
	GLH.TAX_STATUS_CODE	TAX_STATUS_CODE,
	GLH.RUNNING_TOTAL_DR	HDR_TOT_DR,
	GLH.RUNNING_TOTAL_CR	HDR_TOT_CR,
	GLH.RUNNING_TOTAL_ACCOUNTED_DR	HDR_TOT_ACC_DR,
	GLH.RUNNING_TOTAL_ACCOUNTED_CR	HDR_TOT_ACC_CR,
	GLH.CURRENCY_CODE	HDR_CURR_CODE,
	GLH.CURRENCY_CONVERSION_DATE	CONVERSION_DATE,
	GLH.CURRENCY_CONVERSION_RATE	CONVERSION_RATE,
	DCT.USER_CONVERSION_TYPE	CONVERSION_TYPE,
	GLH.BUDGET_VERSION_ID	BUDGET_VERSION_ID,
	GLH.ENCUMBRANCE_TYPE_ID	ENCUMBRANCE_TYPE_ID,
	GLH.EXTERNAL_REFERENCE	HDR_EXTREFERENCE,
	GLH.LAST_UPDATE_DATE	HDR_LAST_UPDATE_DATE,
	GLH.DEFAULT_EFFECTIVE_DATE	HDR_EFF_DATE,
                GLH.DOC_SEQUENCE_ID          DOC_SEQ_ID,
	DOCSEQ.NAME		DOC_SEQ_NAME,
	GLH.DOC_SEQUENCE_VALUE	DOC_SEQ_VALUE,
	FU.USER_NAME		HDR_LAST_UPDATED_BY,
	GJS.USER_JE_SOURCE_NAME	HDR_SOURCE,
	GJC.USER_JE_CATEGORY_NAME	HDR_CATEGORY,

	GLL.JE_LINE_NUM		JE_LINE_NUM,
	GLL.TAX_CODE_ID		TAX_CODE_ID,
	GLL.TAX_TYPE_CODE	TAX_TYPE_CODE,
	GLL.DESCRIPTION		LINE_DESC,
	GLL.ENTERED_DR		ENTERED_DR,
	GLL.ENTERED_CR		ENTERED_CR,
	GLL.ACCOUNTED_DR	ACCOUNTED_DR,
	GLL.ACCOUNTED_CR	ACCOUNTED_CR,
	GLL.STAT_AMOUNT		STAT_AMOUNT,
	GLL.EFFECTIVE_DATE	EFFECTIVE_DATE,
	GLL.REFERENCE_1		REFERENCE1,
	GLL.REFERENCE_2		REFERENCE2,
	GLL.REFERENCE_3		REFERENCE3,
	GLL.REFERENCE_4		REFERENCE4,
	GLL.REFERENCE_5		REFERENCE5,
	GLL.REFERENCE_6		REFERENCE6,
	GLL.REFERENCE_7		REFERENCE7,
	GLL.REFERENCE_8		REFERENCE8,
	GLL.REFERENCE_9		REFERENCE9,
	GLL.REFERENCE_10		REFERENCE10,
	SUBDOCSEQ.NAME		SUB_DOC_SEQ_NAME,
                GLL.SUBLEDGER_DOC_SEQUENCE_ID SUB_DOC_SEQ_ID,
	GLL.SUBLEDGER_DOC_SEQUENCE_VALUE	SUB_DOC_SEQ_VAL

 FROM    GL_LEDGERS LGR,        GL_JE_BATCHES 		GLB,
        GL_JE_HEADERS 		GLH,
        GL_JE_SOURCES        		GJS,
        GL_JE_CATEGORIES       		GJC,
        GL_JE_LINES 			GLL,
        GL_DAILY_CONVERSION_TYPES      DCT,
        FND_DOCUMENT_SEQUENCES 	DOCSEQ, 
        FND_DOCUMENT_SEQUENCES 	SUBDOCSEQ,
        GL_CODE_COMBINATIONS	CC,
        FND_USER 			FU
		
WHERE GLH.LEDGER_ID = LGR.LEDGER_ID
 AND  GLH.JE_SOURCE = GJS.JE_SOURCE_NAME
 AND  GLH.JE_CATEGORY  =  GJC.JE_CATEGORY_NAME
 AND  GLH.LAST_UPDATED_BY = FU.USER_ID
 AND  GLB.JE_BATCH_ID = GLH.JE_BATCH_ID
 AND  GLH.DOC_SEQUENCE_ID = DOCSEQ.DOC_SEQUENCE_ID(+)
 AND  GLL.SUBLEDGER_DOC_SEQUENCE_ID = SUBDOCSEQ.DOC_SEQUENCE_ID(+)
 AND DCT.CONVERSION_TYPE (+) = GLH.CURRENCY_CONVERSION_TYPE
 
 AND GLH.LEDGER_ID=nvl(:P_LEDGER_ID , GLH.LEDGER_ID) 
 AND GLB.STATUS=nvl(:P_STATUS ,GLB.STATUS) 
 AND GLH.CURRENCY_CODE=nvl(:P_CURRENCY , GLH.CURRENCY_CODE) 
 AND GLH.DEFAULT_EFFECTIVE_DATE between :P_START_DATE  and  :P_END_DATE 
 AND GLB.JE_BATCH_ID=nvl(:P_BATCH_NAME ,GLB.JE_BATCH_ID)  
 AND GLH.JE_CATEGORY=nvl(:P_CATEGORY ,GLH.JE_CATEGORY) 
 AND  GLH.DOC_SEQUENCE_VALUE between  :P_START_DOC_VALUE and  :P_END_DOC_VALUE
 
      
  
  

**************************************************

SELECT   
    	LGR.NAME		LEDGER_NAME,
		LGR.CURRENCY_CODE	LEDGER_CURRENCY,
		LGR.LEDGER_ID                       LEDGER_ID,
		GLB.JE_BATCH_ID		BATCH_ID,
		GLB.NAME		BATCH_NAME,
		GLB.DESCRIPTION		BATCH_DESC,
		GLB.STATUS		BATCH_STATUS_CODE,
		GLB.POSTED_DATE		BATCH_POSTED_DATE,
		GLB.DEFAULT_PERIOD_NAME	BATCH_PERIOD_NAME,
		GLB.DEFAULT_EFFECTIVE_DATE	BATCH_EFFECTIVE_DATE,
		GLB.ACTUAL_FLAG			ACTUAL_FLAG, 
		GLB.AVERAGE_JOURNAL_FLAG	AVERAGE_JOURNAL_FLAG,
		GLB.APPROVAL_STATUS_CODE	APPROVAL_STATUS_CODE,
		GLB.BUDGETARY_CONTROL_STATUS	BUD_CONTROL_STATUS,
		GLB.RUNNING_TOTAL_DR	BATCH_TOT_DR,
		GLB.RUNNING_TOTAL_CR	BATCH_TOT_CR,
		GLB.RUNNING_TOTAL_ACCOUNTED_DR	BATCH_TOT_ACC_DR,
		GLB.RUNNING_TOTAL_ACCOUNTED_CR	BATCH_TOT_ACC_CR,
		GLB.DATE_CREATED	BATCH_DATE_CREATED,

	GLH.JE_HEADER_ID		HDR_ID,
	GLH.NAME		HDR_NAME,
	GLH.DESCRIPTION		HDR_DESC,
	GLH.TAX_STATUS_CODE	TAX_STATUS_CODE,
	GLH.RUNNING_TOTAL_DR	HDR_TOT_DR,
	GLH.RUNNING_TOTAL_CR	HDR_TOT_CR,
	GLH.RUNNING_TOTAL_ACCOUNTED_DR	HDR_TOT_ACC_DR,
	GLH.RUNNING_TOTAL_ACCOUNTED_CR	HDR_TOT_ACC_CR,
	GLH.CURRENCY_CODE	HDR_CURR_CODE,
	GLH.CURRENCY_CONVERSION_DATE	CONVERSION_DATE,
	GLH.CURRENCY_CONVERSION_RATE	CONVERSION_RATE,
	DCT.USER_CONVERSION_TYPE	CONVERSION_TYPE,
	GLH.BUDGET_VERSION_ID	BUDGET_VERSION_ID,
	GLH.ENCUMBRANCE_TYPE_ID	ENCUMBRANCE_TYPE_ID,
	GLH.EXTERNAL_REFERENCE	HDR_EXTREFERENCE,
	GLH.LAST_UPDATE_DATE	HDR_LAST_UPDATE_DATE,
	GLH.DEFAULT_EFFECTIVE_DATE	HDR_EFF_DATE,
                GLH.DOC_SEQUENCE_ID          DOC_SEQ_ID,
	DOCSEQ.NAME		DOC_SEQ_NAME,
	GLH.DOC_SEQUENCE_VALUE	DOC_SEQ_VALUE,
	FU.USER_NAME		HDR_LAST_UPDATED_BY,
	GJS.USER_JE_SOURCE_NAME	HDR_SOURCE,
	GJC.USER_JE_CATEGORY_NAME	HDR_CATEGORY,

	GLL.JE_LINE_NUM		JE_LINE_NUM,
	GLL.TAX_CODE_ID		TAX_CODE_ID,
	GLL.TAX_TYPE_CODE	TAX_TYPE_CODE,
	GLL.DESCRIPTION		LINE_DESC,
	GLL.ENTERED_DR		ENTERED_DR,
	GLL.ENTERED_CR		ENTERED_CR,
	GLL.ACCOUNTED_DR	ACCOUNTED_DR,
	GLL.ACCOUNTED_CR	ACCOUNTED_CR,
	GLL.STAT_AMOUNT		STAT_AMOUNT,
	GLL.EFFECTIVE_DATE	EFFECTIVE_DATE,
	GLL.REFERENCE_1		REFERENCE1,
	GLL.REFERENCE_2		REFERENCE2,
	GLL.REFERENCE_3		REFERENCE3,
	GLL.REFERENCE_4		REFERENCE4,
	GLL.REFERENCE_5		REFERENCE5,
	GLL.REFERENCE_6		REFERENCE6,
	GLL.REFERENCE_7		REFERENCE7,
	GLL.REFERENCE_8		REFERENCE8,
	GLL.REFERENCE_9		REFERENCE9,
	GLL.REFERENCE_10		REFERENCE10,
	SUBDOCSEQ.NAME		SUB_DOC_SEQ_NAME,
                GLL.SUBLEDGER_DOC_SEQUENCE_ID SUB_DOC_SEQ_ID,
	GLL.SUBLEDGER_DOC_SEQUENCE_VALUE	SUB_DOC_SEQ_VAL

 FROM    GL_LEDGERS LGR,        GL_JE_BATCHES 		GLB,
        GL_JE_HEADERS 		GLH,
        GL_JE_SOURCES        		GJS,
        GL_JE_CATEGORIES       		GJC,
        GL_JE_LINES 			GLL,
        GL_DAILY_CONVERSION_TYPES      DCT,
        FND_DOCUMENT_SEQUENCES 	DOCSEQ, 
        FND_DOCUMENT_SEQUENCES 	SUBDOCSEQ,
        GL_CODE_COMBINATIONS	CC,
        FND_USER 			FU
		
WHERE GLH.LEDGER_ID = LGR.LEDGER_ID
 AND  GLH.JE_SOURCE = GJS.JE_SOURCE_NAME
 AND  GLH.JE_CATEGORY  =  GJC.JE_CATEGORY_NAME
 AND  GLH.LAST_UPDATED_BY = FU.USER_ID
 AND  GLB.JE_BATCH_ID = GLH.JE_BATCH_ID
 AND  GLH.DOC_SEQUENCE_ID = DOCSEQ.DOC_SEQUENCE_ID(+)
 AND  GLL.SUBLEDGER_DOC_SEQUENCE_ID = SUBDOCSEQ.DOC_SEQUENCE_ID(+)
 AND DCT.CONVERSION_TYPE (+) = GLH.CURRENCY_CONVERSION_TYPE
 AND P_LEDGER_ID
 
 
 

******************************************
SELECT    &P_HINT_CLAUSE
    	LGR.NAME		LEDGER_NAME,
	LGR.CURRENCY_CODE	LEDGER_CURRENCY,
                LGR.LEDGER_ID                       LEDGER_ID,
	GLB.JE_BATCH_ID		BATCH_ID,
    	GLB.NAME		BATCH_NAME,
	GLB.DESCRIPTION		BATCH_DESC,
	GLB.STATUS		BATCH_STATUS_CODE,
     	GLB.POSTED_DATE		BATCH_POSTED_DATE,
     	GLB.DEFAULT_PERIOD_NAME	BATCH_PERIOD_NAME,
     	GLB.DEFAULT_EFFECTIVE_DATE	BATCH_EFFECTIVE_DATE,
        	GLB.ACTUAL_FLAG			ACTUAL_FLAG, 
	GLB.AVERAGE_JOURNAL_FLAG	AVERAGE_JOURNAL_FLAG,
	GLB.APPROVAL_STATUS_CODE	APPROVAL_STATUS_CODE,
	GLB.BUDGETARY_CONTROL_STATUS	BUD_CONTROL_STATUS,
	GLB.RUNNING_TOTAL_DR	BATCH_TOT_DR,
	GLB.RUNNING_TOTAL_CR	BATCH_TOT_CR,
	GLB.RUNNING_TOTAL_ACCOUNTED_DR	BATCH_TOT_ACC_DR,
	GLB.RUNNING_TOTAL_ACCOUNTED_CR	BATCH_TOT_ACC_CR,
	GLB.DATE_CREATED	BATCH_DATE_CREATED,

	GLH.JE_HEADER_ID		HDR_ID,
	GLH.NAME		HDR_NAME,
	GLH.DESCRIPTION		HDR_DESC,
	GLH.TAX_STATUS_CODE	TAX_STATUS_CODE,
	GLH.RUNNING_TOTAL_DR	HDR_TOT_DR,
	GLH.RUNNING_TOTAL_CR	HDR_TOT_CR,
	GLH.RUNNING_TOTAL_ACCOUNTED_DR	HDR_TOT_ACC_DR,
	GLH.RUNNING_TOTAL_ACCOUNTED_CR	HDR_TOT_ACC_CR,
	GLH.CURRENCY_CODE	HDR_CURR_CODE,
	GLH.CURRENCY_CONVERSION_DATE	CONVERSION_DATE,
	GLH.CURRENCY_CONVERSION_RATE	CONVERSION_RATE,
	DCT.USER_CONVERSION_TYPE	CONVERSION_TYPE,
	GLH.BUDGET_VERSION_ID	BUDGET_VERSION_ID,
	GLH.ENCUMBRANCE_TYPE_ID	ENCUMBRANCE_TYPE_ID,
	GLH.EXTERNAL_REFERENCE	HDR_EXTREFERENCE,
	GLH.LAST_UPDATE_DATE	HDR_LAST_UPDATE_DATE,
	GLH.DEFAULT_EFFECTIVE_DATE	HDR_EFF_DATE,
                GLH.DOC_SEQUENCE_ID          DOC_SEQ_ID,
	DOCSEQ.NAME		DOC_SEQ_NAME,
	GLH.DOC_SEQUENCE_VALUE	DOC_SEQ_VALUE,
	FU.USER_NAME		HDR_LAST_UPDATED_BY,
	GJS.USER_JE_SOURCE_NAME	HDR_SOURCE,
	GJC.USER_JE_CATEGORY_NAME	HDR_CATEGORY,

	GLL.JE_LINE_NUM		JE_LINE_NUM,
	GLL.TAX_CODE_ID		TAX_CODE_ID,
	GLL.TAX_TYPE_CODE	TAX_TYPE_CODE,
	GLL.DESCRIPTION		LINE_DESC,
	GLL.ENTERED_DR		ENTERED_DR,
	GLL.ENTERED_CR		ENTERED_CR,
	GLL.ACCOUNTED_DR	ACCOUNTED_DR,
	GLL.ACCOUNTED_CR	ACCOUNTED_CR,
	GLL.STAT_AMOUNT		STAT_AMOUNT,
	GLL.EFFECTIVE_DATE	EFFECTIVE_DATE,
	GLL.REFERENCE_1		REFERENCE1,
	GLL.REFERENCE_2		REFERENCE2,
	GLL.REFERENCE_3		REFERENCE3,
	GLL.REFERENCE_4		REFERENCE4,
	GLL.REFERENCE_5		REFERENCE5,
	GLL.REFERENCE_6		REFERENCE6,
	GLL.REFERENCE_7		REFERENCE7,
	GLL.REFERENCE_8		REFERENCE8,
	GLL.REFERENCE_9		REFERENCE9,
	GLL.REFERENCE_10		REFERENCE10,
	SUBDOCSEQ.NAME		SUB_DOC_SEQ_NAME,
                GLL.SUBLEDGER_DOC_SEQUENCE_ID SUB_DOC_SEQ_ID,
	GLL.SUBLEDGER_DOC_SEQUENCE_VALUE	SUB_DOC_SEQ_VAL,
	 &SELECT_ACCOUNT		ACCOUNT,
	&SELECT_BAL_SEGMENT	BAL_SEG_VAL,
	&SELECT_ACCT_SEGMENT	ACCT_SEG_VAL,
	&SELECT_COST_CTR_SEGMENT	COST_CTR_SEG_VAL,
	&SELECT_SECONDARY_SEGMENT	ADDITIONAL_SEGMENT_VALUE

 FROM     &P_PERF_FROM
               &P_JOURNAL_FROM_CLAUSE 
               &P_LEDGER_FROM
WHERE GLH.LEDGER_ID = LGR.LEDGER_ID
 &P_LEDGER_WHERE
 AND  GLH.JE_SOURCE = GJS.JE_SOURCE_NAME
 AND  GLH.JE_CATEGORY  =  GJC.JE_CATEGORY_NAME
 AND  GLH.LAST_UPDATED_BY = FU.USER_ID
 AND  GLB.JE_BATCH_ID = GLH.JE_BATCH_ID
 AND  GLH.DOC_SEQUENCE_ID = DOCSEQ.DOC_SEQUENCE_ID(+)
 AND  GLL.SUBLEDGER_DOC_SEQUENCE_ID = SUBDOCSEQ.DOC_SEQUENCE_ID(+)
 AND DCT.CONVERSION_TYPE (+) = GLH.CURRENCY_CONVERSION_TYPE
&P_POSTING_STATUS
&P_HEADER_POSTING_STATUS
&P_DAS_WHERE
&P_CURRENCY_WHERE
&P_ACTUAL_TYPE_WHERE
&P_BATCH_WHERE
&P_SOURCE_WHERE
&P_CATEGORY_WHERE
&P_BAL_WHERE
&P_DOC_ID_WHERE
&P_DOC_VAL_WHERE
&P_SUB_DOC_ID_WHERE
&P_SUB_DOC_VAL_WHERE
&P_PERIOD_WHERE
&P_CONTRA_ACCOUNT_WHERE 
 &P_JOURNAL_DATE_WHERE
&P_JOURNAL_UPD_DATE_WHERE
&P_JOURNAL_LAST_UPD_WHERE
&P_AFF_WHERE
&P_AMOUNT_WHERE
&P_JOURNAL_WHERE_CLAUSE
 
